CREATE TABLE IF NOT EXISTS product (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_product_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS stock (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT    NOT NULL,
    quantity   BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_stock_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE IF NOT EXISTS stock_transaction (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL,
    type       VARCHAR(20) NOT NULL,
    quantity   BIGINT      NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_stock_transaction_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stock_product ON stock (product_id);
